"""initial schema

Revision ID: 6ef298ccde5b
Revises: 
Create Date: 2026-09-07 15:28:55.054552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef298ccde5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPERATIONS_ADMIN', 'MONITOR_ADMIN', name='admin_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('sector', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('initial_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'HALTED', 'DELISTED', name='company_status'), nullable=False),
    sa.Column('liquidity_depth', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fundamentals', sa.JSON(), nullable=False),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('market_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'LIVE', 'PAUSED', 'EMERGENCY_FROZEN', 'ENDING', 'CLOSED', name='market_state_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_paused_seconds', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sequence_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('invitation_code', sa.String(length=32), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LOCKED', 'DISQUALIFIED', name='team_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_index(op.f('ix_teams_invitation_code'), 'teams', ['invitation_code'], unique=True)
    op.create_table('holdings',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_purchase_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'company_id')
    )
    op.create_table('market_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SINGLE_COMPANY', 'MULTI_COMPANY', 'SECTOR_WIDE', 'MARKET_WIDE', name='market_event_type'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'EXECUTED', 'CANCELLED', name='market_event_status'), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('affected_company_ids', sa.JSON(), nullable=False),
    sa.Column('impact_direction', sa.String(length=20), nullable=False),
    sa.Column('impact_range_min', sa.Float(), nullable=False),
    sa.Column('impact_range_max', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ai_prompt', sa.String(length=2000), nullable=True),
    sa.Column('ai_reasoning', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('news',
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('type', sa.Enum('COMPANY_NEWS', 'CLUE', 'MARKET_NEWS', 'BREAKING_NEWS', name='news_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'CANCELLED', name='news_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('portfolios',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('return_percent', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_company_id'), 'price_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_sequence_number'), 'price_snapshots', ['sequence_number'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', name='user_status'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_table('news_companies',
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'company_id')
    )
    op.create_table('news_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='trade_type'), nullable=False),
    sa.Column('currency_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('execution_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.Enum('EXECUTED', 'REJECTED', name='trade_status'), nullable=False),
    sa.Column('rejection_reason', sa.Enum('INSUFFICIENT_FUNDS', 'INSUFFICIENT_SHARES', 'MARKET_PAUSED', 'MARKET_CLOSED', 'MARKET_FROZEN', 'INVALID_ORDER', 'COMPANY_HALTED', 'NONE', name='rejection_reason'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trade_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_trades_idempotency_key')
    )
    op.create_index(op.f('ix_trades_company_id'), 'trades', ['company_id'], unique=False)
    op.create_index(op.f('ix_trades_idempotency_key'), 'trades', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_trades_team_id'), 'trades', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_team_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_idempotency_key'), table_name='trades')
    op.drop_index(op.f('ix_trades_company_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('news_revisions')
    op.drop_table('news_companies')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_snapshots_sequence_number'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_company_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('portfolios')
    op.drop_table('news')
    op.drop_table('market_events')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_teams_invitation_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('market_state')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
